### ISSUE TITLE
Issue with dependency on flatmap-stream via ps-tree

### ISSUE THREAD

**Issue by darklingChaz** [mysticatea/npm-run-all#155] opened 2018-11-27 15:39 UTC
npm-run-all is trying to pull down flatmap-stream as a dependency of ps-tree@1.1.0. 

flatmap-stream has been removed from npm. See https://github.com/remy/nodemon/issues/1468.

Newest version ps-tree@1.1.2 is fixed.

- sorry, don't have time to fork and request  :(

**Comment by TehShrike** [comment] 2018-11-27 15:59
Duplicate of #149, #150, #152, #153, #154

This was fixed in v4.1.5

**Comment by darklingChaz** [comment] 2018-11-27 16:00
Cheers!

**Closed** 2018-11-27 21:47 UTC
