### ISSUE TITLE
You have a backdoor script installed sir

### ISSUE THREAD

**Issue by JasonShin** [mysticatea/npm-run-all#152] opened 2018-11-27 08:02 UTC
It starts from `ps-tree`

check this: https://github.com/indexzero/ps-tree/issues/36

and check https://github.com/dominictarr/event-stream/issues/115

**Comment by mysticatea** [comment] 2018-11-27 08:22
Thank you for the report.

However, this is a duplicate of #149 and #150.
But I have already published [v4.1.5](https://github.com/mysticatea/npm-run-all/releases/tag/v4.1.5) to address it on the last week.

**Closed by mysticatea** 2018-11-27 08:22 UTC
