### ISSUE TITLE
fails with lerna and .npmrc loglevel=silent

### ISSUE THREAD

**Issue by GuyMograbi** [mysticatea/npm-run-all#158] opened 2018-12-29 02:17 UTC
steps to reproduce: 

- set npm loglevel to be silent by adding file .npmrc property loglevel=true
- use lerna in your project and a postinstall script using npm-run-all. Lets assume it is "npm-run-all demo"
- install project using `lerna bootstrap`

==> npm-run-all tries to spawn a command by running `lerna run --silent demo`
lerna does not know how to handle the `--silent` flag and fails. 

This used to work in previous versions.

**Comment by mysticatea** [comment] 2018-12-29 13:58
Thank you for the report.

But this package is to run `npm-scripts`, it doesn't guarantee to work fine on other tools.

> This used to work in previous versions.

What do you mean? This behavior has not been changed since v1.5.0 (Jan 2016).

**Comment by mysticatea** [comment] 2018-12-29 14:03
`npm-run-all` finds the command which runs `npm-scripts` by the environment variable `NPM_EXECPATH`. The problem looks that `lerna` sets `NPM_EXECPATH` by itself but it doesn't compatible to `npm run` command. Would you confirm that?

**Comment by GuyMograbi** [comment] 2018-12-29 16:43
Sounds right.

In version 3.1.2 it works great.
I downgraded back to it.

**Comment by mysticatea** [comment] 2018-12-30 01:59
OK, so I recommend to open an issue on lerna repo. I'm closing as not problem in this repo.

**Closed by mysticatea** 2018-12-30 01:59 UTC

**Comment by GuyMograbi** [comment] 2018-12-30 02:34
I disagree. The feature where you read "silent" and blindly pass it along
to lerna is not lerna's problem.

**Comment by GuyMograbi** [comment] 2018-12-30 02:37
@mysticatea more so, I don't understand the motivation behind reading "silent" from config. 
if npm is configured to be silent, why do you need to explicitly send `--silent` to the command line? 

Shouldn't the configuration just find its way to the spawned `npm`?

This behavior was changed in `npm-run-all` and it is not clear why.

**Comment by mysticatea** [comment] 2018-12-30 05:11
The problem is that `lerna` sets a command which is not compatible with npm to `NPM_EXECPATH`.

**Comment by GuyMograbi** [comment] 2018-12-30 06:32
@mysticatea the release not does not explain why you add `--silent` explicitly. 

loglevel is set to `silent` through `.npmrc`. 
Why does `npm-run-all` decide this justifies a flag in the command line? 

I opened a bug in lerna, but I still think it's not their problem. 

see lerna bug at: https://github.com/lerna/lerna/issues/1842

**Comment by mysticatea** [comment] 2018-12-30 07:54
> the release notes does not explain why you add --silent explicitly.

Because that behavior has not been changed since v1.5.0.

> Why does npm-run-all decide this justifies a flag in the command line?

There are two steps:

1. collect options from CLI and environment variables then merge those into an object. (to be sure, it doesn't read `.npmrc`. Probably `lerna` reads `.npmrc` and set it to environment variables.) This happens in CLI command implementation.
2. to give the child process the options object, some options are passed as environment variables, some options are passed as CLI options. This happens in Node.js API implementation that the CLI uses. At this time, the Node.js API doesn't know where `options.silent` value came from.
