### ISSUE TITLE
tests run very slowly

### ISSUE THREAD

**Issue by JuanCaicedo** [mysticatea/npm-run-all#77] opened 2016-12-26 14:15 UTC
I ran `npm test` and one of the tasks took a very long time. It was executing
```bash
eslint src test "test-workspace/tasks/*"
```
I can try to add some timing data. For reference, I was using node v4.4.5

**Comment by JuanCaicedo** [comment] 2016-12-26 15:36
I'm sorry, the command that was taking a long time was actually
```
nyc --require babel-register mocha "test/*.js" --reporter progress --timeout 60000
```

**Comment by JuanCaicedo** [comment] 2016-12-26 15:40
Might be related, if I run `npm run watch`, I see a lot of tests fail

**Comment by mysticatea** [comment] 2016-12-27 04:24
Yes, tests are really slow. [This CI has spent 2.5 hours](https://travis-ci.org/mysticatea/npm-run-all/builds/180279338).
The cause is 3.

1. that tests create many processes; `npm run a` is executed by `sh` then `#!/usr/bin/env node` executes `env` then it executes `node` with `npm/bin/cli.js` then it executes `sh` with the script `a` then the script would use `node`.
2. Tests are using timer to verify the order of tasks and the cancel of tasks.
3. Also many processes import `babel` which is heavy.

**Comment by mysticatea** [comment] 2016-12-27 08:22
There is the plan to improve this.

- Using `NPM_EXECPATH` environment variable would reduce intermediate processes of `npm run a`.
  I will use it on `npm-run-all@4.0.0`.
- `npm-run-all@4.0.0` will drop supports of Node.js 0.10/0.12, so it would be able to stop using `babel`.

**Comment by JuanCaicedo** [comment] 2016-12-27 13:46
`NPM_EXECPATH` sounds like a good fix, I can test it locally. 

Dropping v0.10/0.12 sounds like a good idea, but maybe the problem is running babel the mocha babel compiler? From what I understand, this interprets the ES6 code at runtime, which is much slower. Something we do at my company is to run a compile step first and then execute our tests against the compiled code. I think that could have huge performance improvements! 😃 Let me know if you would like to do that and I can help

**Comment by mysticatea** [comment] 2016-12-31 15:28
https://travis-ci.org/mysticatea/npm-run-all/builds
I dropped supports for Node 0.x and I stopped using `babel` to transpile. Then it made faster tests.
So I'm closing this issue.

Thank you!

**Closed by mysticatea** 2016-12-31 15:28 UTC
